name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_xray:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        regions:
          - name: hk
            code: hkg
          - name: us
            code: sea
          - name: eu
            code: lhr
    env:
      FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy 
        working-directory: ./xray
        env:
          XRAY_USER: ${{ secrets.XRAY_USER }}
        run: |
          jq '.inbounds.[0].settings.clients.[0].id = $ENV.XRAY_USER' ./config.json > ./config.json.tmp
          mv config.json.tmp config.json
          flyctl apps create bonjour-xray-${{ matrix.regions.name }} || true
          flyctl deploy --app bonjour-xray-${{ matrix.regions.name }} --regions ${{ matrix.regions.code }}
          flyctl --app bonjour-xray-${{ matrix.regions.name }} scale count 1
