name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_xray:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        regions:
          - hk hkg
          - us sea
          - eu lhr
    env:
      FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy 
        working-directory: ./xray
        env:
          XRAY_USER: ${{ secrets.XRAY_USER }}
        run: |
          jq '.inbounds.[0].settings.clients.[0].id = $ENV.XRAY_USER' ./config.json > ./config.json.tmp
          mv config.json.tmp config.json
          cat ./config.json

          r=(${{ matrix.regions }})
          app=${r[0]}
          region=${r[1]}
          echo $app
          echo $region
          # flyctl apps create bonjour-xray-"$app" || true
          # flyctl deploy --app bonjour-xray-"$app" --regions "$region"
          # flyctl --app bonjour-xray-"$app" scale count 1
